"""
Scans every GLB in the frontend's asset folder and measures each one's
TRUE rendered size using trimesh - which correctly applies node-level
transforms. Captures each model's pivot offset (min_x/min_y/min_z) so
placement can correct for internal origin quirks, including vertical
(Y-axis) offsets that cause buildings to render at inconsistent heights
relative to each other.

Run manually: python -m app.city_builder.measure_assets
"""
import statistics
from pathlib import Path

import trimesh

MODELS_DIR = Path(__file__).resolve().parents[3] / "frontend" / "src" / "assets" / "models"


class MissingModelAssetsError(RuntimeError):
    """Raised when the GLB asset folder is missing or holds no models to measure."""


CATEGORY_TARGET_SIZES = {
    "road": 10.0,
    "building": 6.0,
    "vehicle": 1.5,
    "prop": 0.6,
}
MANUAL_SCALE_OVERRIDES = {}
ASSET_SPECIFIC_TARGET_SIZES = {
    "traffic-light.glb": 4.0,
    "atm.glb": 2.5,
}

CATEGORY_KEYWORDS = {
    "road": ["road"],
    "vehicle": ["car", "bike", "taxi", "scooter", "bus", "truck", "auto", "van", "motor", "cycle"],
    "prop": ["atm", "traffic-light", "coin"],
}


def measure_all_models() -> list[dict]:
    results = []
    for glb_path in sorted(MODELS_DIR.glob("*.glb")):
        scene = trimesh.load(glb_path, force="scene")
        bounds = scene.bounds

        width = round(float(bounds[1][0] - bounds[0][0]), 3)
        height = round(float(bounds[1][1] - bounds[0][1]), 3)
        depth = round(float(bounds[1][2] - bounds[0][2]), 3)

        results.append({
            "filename": glb_path.name,
            "width": width,
            "height": height,
            "depth": depth,
            "min_x": round(float(bounds[0][0]), 5),
            "min_y": round(float(bounds[0][1]), 5),
            "min_z": round(float(bounds[0][2]), 5),
        })
    return results


def categorize_filename(filename: str) -> str:
    name_lower = filename.lower()
    for category, keywords in CATEGORY_KEYWORDS.items():
        if any(keyword in name_lower for keyword in keywords):
            return category
    return "building"


def compute_scale_corrections(measurements: list[dict]) -> list[dict]:
    if not measurements:
        reason = (
            "does not exist" if not MODELS_DIR.exists()
            else "exists but contains no .glb files"
        )
        raise MissingModelAssetsError(
            f"No 3D models to measure: {MODELS_DIR} {reason}.\n"
            "These are custom binary .glb assets that are not generated by the build "
            "and are not recoverable by reinstalling dependencies. Restore them from a "
            "backup, a teammate, or another checkout of the project before running the "
            "city builder."
        )

    largest_dims = [max(m["width"], m["height"], m["depth"]) for m in measurements]
    median_largest = statistics.median(largest_dims)

    results = []
    for m, largest in zip(measurements, largest_dims):
        category = categorize_filename(m["filename"])
        target_size = ASSET_SPECIFIC_TARGET_SIZES.get(m["filename"], CATEGORY_TARGET_SIZES[category])

        is_outlier = largest > median_largest * 10
        if m["filename"] in MANUAL_SCALE_OVERRIDES:
            correction = MANUAL_SCALE_OVERRIDES[m["filename"]]
        else:
            correction = target_size / largest if largest > 0 else 1.0

        results.append({
            **m,
            "category": category,
            "largest_dimension": round(largest, 3),
            "is_outlier": is_outlier,
            "scale_correction": round(correction, 5),
        })
    return results


def apply_render_offset(items: list[dict]) -> list[dict]:
    corrected = []
    for item in items:
        scale = item["scale_correction"]
        min_x, min_z = item["min_x"], item["min_z"]
        min_y = item.get("min_y", 0)

        if "width" in item:
            local_width = item["width"]
            local_depth = item["depth"]
        else:
            local_width = item["scaled_width"] / scale
            local_depth = item["scaled_depth"] / scale

        max_x = min_x + local_width
        max_z = min_z + local_depth
        rotation = item.get("rotation_y", 0) % 360

        if rotation == 0:
            world_min_x_source, world_min_z_source = min_x, min_z
        elif rotation == 90:
            world_min_x_source, world_min_z_source = min_z, -max_x
        elif rotation == 180:
            world_min_x_source, world_min_z_source = -max_x, -max_z
        elif rotation == 270:
            world_min_x_source, world_min_z_source = -max_z, min_x
        else:
            world_min_x_source, world_min_z_source = min_x, min_z

        render_x = item["position_x"] - world_min_x_source * scale
        render_z = item["position_z"] - world_min_z_source * scale
        render_y = -min_y * scale

        corrected.append({
            **item,
            "render_x": round(render_x, 3),
            "render_y": round(render_y, 3),
            "render_z": round(render_z, 3),
        })
    return corrected


if __name__ == "__main__":
    raw = measure_all_models()
    corrected = compute_scale_corrections(raw)
    for entry in corrected:
        flag = " <-- OUTLIER" if entry["is_outlier"] else ""
        print(f"{entry['filename']:25} [{entry['category']:9}] largest={entry['largest_dimension']:>8}  correction={entry['scale_correction']:>8}{flag}")